// <auto-generated />
using System;
using HikoukiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikoukiApi.Migrations
{
    [DbContext(typeof(HikoukiDbContext))]
    [Migration("20260531031112_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HikoukiApi.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftTypeCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("aircraft_type_code_id");

                    b.Property<int?>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("airline_id");

                    b.Property<string>("AlternateOperatorName")
                        .HasColumnType("text")
                        .HasColumnName("alternate_operator_name");

                    b.Property<bool>("IsGovOrMilitary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_gov_or_military");

                    b.Property<bool>("IsSpecialLivery")
                        .HasColumnType("boolean")
                        .HasColumnName("is_special_livery");

                    b.Property<string>("LineNumber")
                        .HasColumnType("text")
                        .HasColumnName("line_number");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("registration");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("serial_number");

                    b.Property<string>("SpecialLiveryName")
                        .HasColumnType("text")
                        .HasColumnName("special_livery_name");

                    b.Property<int?>("TypeCodeVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("type_code_variant_id");

                    b.HasKey("Id")
                        .HasName("pk_airplanes");

                    b.HasIndex("AircraftTypeCodeId")
                        .HasDatabaseName("ix_airplanes_aircraft_type_code_id");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("ix_airplanes_airline_id");

                    b.HasIndex("TypeCodeVariantId")
                        .HasDatabaseName("ix_airplanes_type_code_variant_id");

                    b.ToTable("airplanes", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftId")
                        .HasColumnType("integer")
                        .HasColumnName("aircraft_id");

                    b.Property<int?>("AirlineId")
                        .HasColumnType("integer")
                        .HasColumnName("airline_id");

                    b.Property<int?>("AirportId")
                        .HasColumnType("integer")
                        .HasColumnName("airport_id");

                    b.Property<string>("AirportLocation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("airport_location");

                    b.Property<string>("Camera")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("camera");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Lens")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lens");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<int?>("TypeCodeVariantId")
                        .HasColumnType("integer")
                        .HasColumnName("type_code_variant_id");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_spotting");

                    b.HasIndex("AircraftId")
                        .HasDatabaseName("ix_aircraft_spotting_aircraft_id");

                    b.HasIndex("AirlineId")
                        .HasDatabaseName("ix_aircraft_spotting_airline_id");

                    b.HasIndex("AirportId")
                        .HasDatabaseName("ix_aircraft_spotting_airport_id");

                    b.HasIndex("TypeCodeVariantId")
                        .HasDatabaseName("ix_aircraft_spotting_type_code_variant_id");

                    b.ToTable("aircraft_spotting", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_type_codes");

                    b.HasIndex("Icao")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_type_codes_icao");

                    b.ToTable("aircraft_type_codes", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<string>("Iata")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("iata");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("icao");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_airlines");

                    b.ToTable("airlines", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .HasColumnType("text")
                        .HasColumnName("alternate_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("country");

                    b.Property<string>("Iata")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("iata");

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_airports");

                    b.HasIndex("Iata")
                        .IsUnique()
                        .HasDatabaseName("ix_airports_iata");

                    b.HasIndex("Icao")
                        .IsUnique()
                        .HasDatabaseName("ix_airports_icao");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftTypeCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("aircraft_type_code_id");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_type_code_variants");

                    b.HasIndex("AircraftTypeCodeId", "VariantName")
                        .IsUnique()
                        .HasDatabaseName("ix_type_code_variants_aircraft_type_code_id_variant_name");

                    b.ToTable("type_code_variants", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.Aircraft", b =>
                {
                    b.HasOne("HikoukiApi.Models.AircraftTypeCode", "TypeCode")
                        .WithMany("Airplanes")
                        .HasForeignKey("AircraftTypeCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_airplanes_aircraft_type_codes_aircraft_type_code_id");

                    b.HasOne("HikoukiApi.Models.Airline", "Airline")
                        .WithMany("Fleet")
                        .HasForeignKey("AirlineId")
                        .HasConstraintName("fk_airplanes_airlines_airline_id");

                    b.HasOne("HikoukiApi.Models.TypeCodeVariant", "TypeCodeVariant")
                        .WithMany()
                        .HasForeignKey("TypeCodeVariantId")
                        .HasConstraintName("fk_airplanes_type_code_variants_type_code_variant_id");

                    b.Navigation("Airline");

                    b.Navigation("TypeCode");

                    b.Navigation("TypeCodeVariant");
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftSpot", b =>
                {
                    b.HasOne("HikoukiApi.Models.Aircraft", "Aircraft")
                        .WithMany("AircraftSpots")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aircraft_spotting_airplanes_aircraft_id");

                    b.HasOne("HikoukiApi.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .HasConstraintName("fk_aircraft_spotting_airlines_airline_id");

                    b.HasOne("HikoukiApi.Models.Airport", "Airport")
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .HasConstraintName("fk_aircraft_spotting_airports_airport_id");

                    b.HasOne("HikoukiApi.Models.TypeCodeVariant", "TypeCodeVariant")
                        .WithMany()
                        .HasForeignKey("TypeCodeVariantId")
                        .HasConstraintName("fk_aircraft_spotting_type_code_variants_type_code_variant_id");

                    b.Navigation("Aircraft");

                    b.Navigation("Airline");

                    b.Navigation("Airport");

                    b.Navigation("TypeCodeVariant");
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.HasOne("HikoukiApi.Models.AircraftTypeCode", null)
                        .WithMany("ModelVariants")
                        .HasForeignKey("AircraftTypeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_code_variants_aircraft_type_codes_aircraft_type_code_id");
                });

            modelBuilder.Entity("HikoukiApi.Models.Aircraft", b =>
                {
                    b.Navigation("AircraftSpots");
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Navigation("Airplanes");

                    b.Navigation("ModelVariants");
                });

            modelBuilder.Entity("HikoukiApi.Models.Airline", b =>
                {
                    b.Navigation("Fleet");
                });
#pragma warning restore 612, 618
        }
    }
}
