// <auto-generated />
using HikoukiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikoukiApi.Migrations
{
    [DbContext(typeof(HikoukiDbContext))]
    partial class HikoukiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Icao")
                        .IsUnique();

                    b.ToTable("AircraftTypeCodes");
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftTypeCodeId")
                        .HasColumnType("integer");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AircraftTypeCodeId", "VariantName")
                        .IsUnique();

                    b.ToTable("TypeCodeVariants");
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.HasOne("HikoukiApi.Models.AircraftTypeCode", null)
                        .WithMany("ModelVariants")
                        .HasForeignKey("AircraftTypeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Navigation("ModelVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
