// <auto-generated />
using HikoukiApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikoukiApi.Migrations
{
    [DbContext(typeof(HikoukiDbContext))]
    partial class HikoukiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icao")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("icao");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manufacturer");

                    b.HasKey("Id")
                        .HasName("pk_aircraft_type_codes");

                    b.HasIndex("Icao")
                        .IsUnique()
                        .HasDatabaseName("ix_aircraft_type_codes_icao");

                    b.ToTable("aircraft_type_codes", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AircraftTypeCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("aircraft_type_code_id");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("variant_name");

                    b.HasKey("Id")
                        .HasName("pk_type_code_variants");

                    b.HasIndex("AircraftTypeCodeId", "VariantName")
                        .IsUnique()
                        .HasDatabaseName("ix_type_code_variants_aircraft_type_code_id_variant_name");

                    b.ToTable("type_code_variants", (string)null);
                });

            modelBuilder.Entity("HikoukiApi.Models.TypeCodeVariant", b =>
                {
                    b.HasOne("HikoukiApi.Models.AircraftTypeCode", null)
                        .WithMany("ModelVariants")
                        .HasForeignKey("AircraftTypeCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_type_code_variants_aircraft_type_codes_aircraft_type_code_id");
                });

            modelBuilder.Entity("HikoukiApi.Models.AircraftTypeCode", b =>
                {
                    b.Navigation("ModelVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
